### ISSUE TITLE
implement Bloom filter datastructure in rust

### ISSUE THREAD

**Issue by ichorid** [dsluijk/rust-ipv8#13]
https://github.com/Tribler/py-ipv8/blob/master/ipv8/messaging/bloomfilter.py

**Comment by ichorid** [comment]
@dsluijk please, look for existing implementations of stuff in C and Rust, instead of doing it by yourself. This will save you a lot of effort. Copy the code if it is license-compatible, or reimplement if it is not.

**Comment by jdonszelmann** [comment]
@ichorid Could you maybe explain to us what py-ipv8 (or tribler?) actually uses the bloom filter for? As far as we could see you only use it in your tests but not in the actual py-ipv8 logic. 
![image](https://user-images.githubusercontent.com/22172241/57971240-a52b3c80-798b-11e9-90ca-22d12a5ea400.png)

**Comment by ichorid** [comment]
It was extensively used by Dispersy, which is gone now. Still, some unused stuff from it remains. If see it is not used in the code, please, file a PR for cleaning it completely from IPv8.

**Comment by ichorid** [comment]
There's a lot of unused stuff in Tribler and IPv8. As you guys are going deeper, you will encounter a lot of cruft. Feel free to question the necessity of its existence, and kill it with fire if you are 100% sure it is dead code!

**Comment by jdonszelmann** [comment]
filing PR

**Comment by ichorid** [comment]
As soon as that will merge, you can close this one :wink:

**Comment by jdonszelmann** [comment]
:ok_hand:

**Comment by jdonszelmann** [comment]
https://github.com/Tribler/py-ipv8/pull/477

**Comment by jdonszelmann** [comment]
merged :D
