### ISSUE TITLE
Serializer

### ISSUE THREAD

**Issue by ichorid** [dsluijk/rust-ipv8#14]
Please, be smart about this. Do not blindly copy IPv8 stuff. If it is possible to use 3rd party code, like Serde, do it. The best serializer is no serializer. If you feel that, to support the use cases we have *at the moment* in Tribler, you can do away with macros: do it.

And for Stroustrup's sake: do not try to conceive your own serializer! Every programmer has an urge to do it, so please control your urges :wink:

**Comment by jdonszelmann** [comment]
solved with #16
