### ISSUE TITLE
Crypto library

### ISSUE THREAD

**Issue by jdonszelmann** [dsluijk/rust-ipv8#26]
the options:

* rust-crypto: + pure rust - not audited, stale
* sodiumoxide: + based on libnacl - not pure rust -> you need to have libnacl which would be a problem on ios devices
* rust_sodium: + compiles libnacl with the rust code which makes. supports cross compiling for ios devices - bindings for nacl so not pure rust.

**Comment by jdonszelmann** [comment]
We mostly voted for rust_sodium.

**Comment by NULLx76** [comment]
we are now also using `openssl` to support all the required ECC curves.

**Comment by ichorid** [comment]
Be aware that different platforms have different implementations of SSL. That is especially true for Mac. Please, be sure to account for these differences.

**Comment by NULLx76** [comment]
We have kept this especially in mind when choosing the libraries. `rust_sodium` specifically has support for a lot of platforms including iOS (it was actually the only one we could find that had that) and `openssl` can be installed "vendored" meaning that it will just download the OpenSSL source and compile it statically.

**Comment by jdonszelmann** [comment]
the result is: now we use Ring and it's way better and faster
